server.port=8080
spring.application.name=smart-inventory-system

# Database
db.url=jdbc:mysql://localhost:3306/smart_inventory?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
db.username=root
db.password=Bhanu@2205
